
export type AcademicEventCategory = 'Inscripciones' | 'Clases' | 'Límite' | 'Asueto' | 'Exámenes' | 'Receso' | 'Cierre' | 'Bajas' | 'Extraordinario';

export interface AcademicEvent {
  date: Date;
  title: string;
  category: AcademicEventCategory;
}

export const academicEvents: AcademicEvent[] = [
  // Tetramestre 1: Enero – Abril
  { date: new Date(2026, 0, 6), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 0, 7), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 0, 8), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 0, 9), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 0, 10), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 0, 12), title: '¡Primer día de clases!', category: 'Clases' },
  { date: new Date(2026, 0, 26), title: 'Límite para cambio de grupo/materia', category: 'Límite' },
  { date: new Date(2026, 1, 2), title: 'Asueto (Día de la Constitución)', category: 'Asueto' },
  { date: new Date(2026, 1, 23), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 1, 24), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 1, 25), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 1, 26), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 1, 27), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 2, 16), title: 'Asueto (Natalicio de Benito Juárez)', category: 'Asueto' },
  { date: new Date(2026, 2, 30), title: 'Receso Académico (Semana Santa)', category: 'Receso' },
  { date: new Date(2026, 2, 31), title: 'Receso Académico (Semana Santa)', category: 'Receso' },
  { date: new Date(2026, 3, 1), title: 'Receso Académico (Semana Santa)', category: 'Receso' },
  { date: new Date(2026, 3, 2), title: 'Receso Académico (Semana Santa)', category: 'Receso' },
  { date: new Date(2026, 3, 3), title: 'Receso Académico (Semana Santa)', category: 'Receso' },
  { date: new Date(2026, 3, 6), title: 'Límite para baja de materias (parcial y total)', category: 'Bajas' },
  { date: new Date(2026, 3, 20), title: 'Límite para cambio de carrera', category: 'Límite' },
  { date: new Date(2026, 3, 22), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 3, 23), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 3, 24), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 3, 27), title: 'Límite de captura de calificaciones', category: 'Cierre' },
  { date: new Date(2026, 3, 28), title: 'Cierre de Periodo', category: 'Cierre' },
  { date: new Date(2026, 3, 29), title: 'Ejecución de CAPPY y Proyecciones', category: 'Cierre' },
  { date: new Date(2026, 3, 30), title: 'Límite MC', category: 'Cierre' },

  // Tetramestre 2: Mayo – Agosto
  { date: new Date(2026, 4, 1), title: 'Asueto (Día del Trabajo)', category: 'Asueto' },
  { date: new Date(2026, 4, 4), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 5), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 6), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 7), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 8), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 9), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 4, 11), title: '¡Primer día de clases!', category: 'Clases' },
  { date: new Date(2026, 4, 18), title: 'Límite para cambio de grupo/materia', category: 'Límite' },
  { date: new Date(2026, 5, 24), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 25), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 26), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 27), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 28), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 29), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 5, 30), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 6, 24), title: 'Límite para baja de materias (parcial y total)', category: 'Bajas' },
  { date: new Date(2026, 7, 7), title: 'Último día de clases y Límite de cambio de carrera', category: 'Clases' },
  { date: new Date(2026, 7, 10), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 7, 11), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 7, 12), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 7, 13), title: 'Límite de captura de calificaciones', category: 'Cierre' },
  { date: new Date(2026, 7, 24), title: 'Cierre de Periodo', category: 'Cierre' },
  { date: new Date(2026, 7, 24), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 25), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 25), title: 'Envío de CAPPY y Proyecciones', category: 'Cierre' },
  { date: new Date(2026, 7, 26), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 26), title: 'Límite MC y Aplicación de Examen Extraordinario', category: 'Cierre' },
  { date: new Date(2026, 7, 26), title: 'Aplicación de Examen Extraordinario', category: 'Extraordinario' },
  { date: new Date(2026, 7, 27), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 27), title: 'Límite envío de resultados de Examen Extraordinario', category: 'Extraordinario' },
  { date: new Date(2026, 7, 28), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 29), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 30), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 7, 31), title: 'Inscripciones de reingreso', category: 'Inscripciones' },

  // Tetramestre 3: Septiembre – Diciembre
  { date: new Date(2026, 8, 1), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 8, 2), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 8, 3), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 8, 4), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 8, 5), title: 'Inscripciones de reingreso', category: 'Inscripciones' },
  { date: new Date(2026, 8, 7), title: '¡Primer día de clases!', category: 'Clases' },
  { date: new Date(2026, 8, 14), title: 'Límite para cambio de grupo/materia', category: 'Límite' },
  { date: new Date(2026, 8, 16), title: 'Asueto (Día de la Independencia)', category: 'Asueto' },
  { date: new Date(2026, 9, 19), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 9, 20), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 9, 21), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 9, 22), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 9, 23), title: 'Exámenes Intermedios', category: 'Exámenes' },
  { date: new Date(2026, 10, 16), title: 'Asueto (Revolución Mexicana)', category: 'Asueto' },
  { date: new Date(2026, 10, 23), title: 'Límite para baja de materias (parcial y total)', category: 'Bajas' },
  { date: new Date(2026, 11, 8), title: 'Límite para cambio de carrera', category: 'Límite' },
  { date: new Date(2026, 11, 9), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 11, 10), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 11, 11), title: 'Exámenes Finales', category: 'Exámenes' },
  { date: new Date(2026, 11, 14), title: 'Límite de captura de calificaciones', category: 'Cierre' },
  { date: new Date(2026, 11, 15), title: 'Cierre de Periodo', category: 'Cierre' },
  { date: new Date(2026, 11, 16), title: 'Ejecución de CAP y Proyecciones', category: 'Cierre' },
  { date: new Date(2026, 11, 17), title: 'Límite MC', category: 'Cierre' },
  { date: new Date(2026, 11, 18), title: 'EXTRA Aplicación y envío de resultados de Examen Extraordinario', category: 'Extraordinario' },
];

    